export const gamingMockData = [
	{
		id: 1,
		title: 'Apex Legends',
		image: 'https://example.com/apex-legends.jpg',
		description: 'Join the battle in this free-to-play battle royale game.',
	},
	{
		id: 2,
		title: 'Minecraft',
		image: 'https://example.com/minecraft.jpg',
		description: 'Build, mine, and survive in a blocky world.',
	},
	{
		id: 3,
		title: 'League of Legends',
		image: 'https://example.com/league-of-legends.jpg',
		description: 'Team up and battle in the iconic MOBA game.',
	},
	{
		id: 4,
		title: 'Fortnite',
		image: 'https://example.com/fortnite.jpg',
		description:
			'Battle your way to victory in this popular battle royale game.',
	},
	{
		id: 5,
		title: 'Call of Duty: Warzone',
		image: 'https://example.com/warzone.jpg',
		description: 'A large-scale battle royale game with a Call of Duty twist.',
	},
	{
		id: 6,
		title: 'Genshin Impact',
		image: 'https://example.com/genshin-impact.jpg',
		description: 'Explore an open-world RPG with breathtaking landscapes.',
	},
	{
		id: 7,
		title: 'The Witcher 3: Wild Hunt',
		image: 'https://example.com/witcher3.jpg',
		description: 'Play as Geralt of Rivia in this epic open-world RPG.',
	},
	{
		id: 8,
		title: 'Valorant',
		image: 'https://example.com/valorant.jpg',
		description:
			'Strategic team-based shooter with unique character abilities.',
	},
	{
		id: 9,
		title: 'Overwatch 2',
		image: 'https://example.com/overwatch2.jpg',
		description: 'Hero-based team shooter with new features in its sequel.',
	},
	{
		id: 10,
		title: 'Cyberpunk 2077',
		image: 'https://example.com/cyberpunk2077.jpg',
		description: 'Experience the futuristic open world of Night City.',
	},
	{
		id: 11,
		title: 'Red Dead Redemption 2',
		image: 'https://example.com/red-dead-redemption2.jpg',
		description: 'Venture into the wild west in this story-driven adventure.',
	},
	{
		id: 12,
		title: 'Hades',
		image: 'https://example.com/hades.jpg',
		description: 'Battle through the Underworld in this roguelike action game.',
	},
	{
		id: 13,
		title: 'Among Us',
		image: 'https://example.com/among-us.jpg',
		description: 'Find the imposter in this thrilling multiplayer party game.',
	},
	{
		id: 14,
		title: 'Rocket League',
		image: 'https://example.com/rocket-league.jpg',
		description: 'High-speed car soccer with explosive action.',
	},
	{
		id: 15,
		title: 'FIFA 23',
		image: 'https://example.com/fifa23.jpg',
		description: 'Play the latest in the popular football simulation series.',
	},
	{
		id: 16,
		title: "Assassin's Creed Valhalla",
		image: 'https://example.com/ac-valhalla.jpg',
		description: 'Lead a Viking invasion in this epic action RPG.',
	},
	{
		id: 17,
		title: 'Dota 2',
		image: 'https://example.com/dota2.jpg',
		description: 'Compete in one of the most popular MOBA games of all time.',
	},
	{
		id: 18,
		title: 'Star Wars Jedi: Fallen Order',
		image: 'https://example.com/jedi-fallen-order.jpg',
		description:
			'Experience an original Star Wars story in this action-adventure game.',
	},
	{
		id: 19,
		title: "No Man's Sky",
		image: 'https://example.com/no-mans-sky.jpg',
		description: 'Explore endless galaxies in this space exploration game.',
	},
	{
		id: 20,
		title: 'Destiny 2',
		image: 'https://example.com/destiny2.jpg',
		description: 'A multiplayer FPS game set in a mysterious sci-fi universe.',
	},
	{
		id: 21,
		title: 'The Sims 4',
		image: 'https://example.com/sims4.jpg',
		description:
			'Create and control a virtual family in this life simulation game.',
	},
	{
		id: 22,
		title: 'Resident Evil Village',
		image: 'https://example.com/resident-evil-village.jpg',
		description: 'Survive terrifying creatures in this horror action game.',
	},
	{
		id: 23,
		title: 'Super Smash Bros. Ultimate',
		image: 'https://example.com/smash-bros-ultimate.jpg',
		description: 'Brawl with iconic characters in this beloved fighting game.',
	},
	{
		id: 24,
		title: 'Super Mario Odyssey',
		image: 'https://example.com/super-mario-odyssey.jpg',
		description: 'Join Mario on a globe-trotting adventure.',
	},
	{
		id: 25,
		title: 'Horizon Zero Dawn',
		image: 'https://example.com/horizon-zero-dawn.jpg',
		description: 'Hunt robotic creatures in a post-apocalyptic world.',
	},
	{
		id: 26,
		title: 'Animal Crossing: New Horizons',
		image: 'https://example.com/animal-crossing.jpg',
		description:
			'Build and design your island life in this relaxing simulation game.',
	},
	{
		id: 27,
		title: 'Final Fantasy VII Remake',
		image: 'https://example.com/ff7-remake.jpg',
		description: 'A modern reimagining of the classic RPG.',
	},
	{
		id: 28,
		title: 'DOOM Eternal',
		image: 'https://example.com/doom-eternal.jpg',
		description: 'Rip and tear through demons in this fast-paced shooter.',
	},
	{
		id: 29,
		title: 'Cuphead',
		image: 'https://example.com/cuphead.jpg',
		description:
			'Experience challenging platforming in this hand-drawn style game.',
	},
	{
		id: 30,
		title: 'Dark Souls III',
		image: 'https://example.com/dark-souls-3.jpg',
		description: 'Prepare to die in this critically acclaimed action RPG.',
	},
	{
		id: 31,
		title: 'Sekiro: Shadows Die Twice',
		image: 'https://example.com/sekiro.jpg',
		description: 'Fight for survival in this challenging ninja action game.',
	},
	{
		id: 32,
		title: 'Elden Ring',
		image: 'https://example.com/elden-ring.jpg',
		description: 'Explore a vast, interconnected world in this action RPG.',
	},
	{
		id: 33,
		title: 'Fortnite: Save the World',
		image: 'https://example.com/fortnite-save-the-world.jpg',
		description: 'Build and survive in this cooperative shooter game.',
	},
	{
		id: 34,
		title: 'F1 2023',
		image: 'https://example.com/f1-2023.jpg',
		description: 'Compete in high-speed F1 races around the world.',
	},
	{
		id: 35,
		title: 'Need for Speed: Heat',
		image: 'https://example.com/nfs-heat.jpg',
		description: 'Race through the streets and build your reputation.',
	},
	{
		id: 36,
		title: 'Gran Turismo 7',
		image: 'https://example.com/gran-turismo-7.jpg',
		description: 'Realistic racing simulation with stunning visuals.',
	},
	{
		id: 37,
		title: 'Far Cry 6',
		image: 'https://example.com/far-cry-6.jpg',
		description: 'Lead a rebellion in this open-world action game.',
	},
	{
		id: 38,
		title: 'Monster Hunter: World',
		image: 'https://example.com/monster-hunter-world.jpg',
		description: 'Hunt giant creatures in an expansive world.',
	},
	{
		id: 39,
		title: 'Ghost of Tsushima',
		image: 'https://example.com/ghost-of-tsushima.jpg',
		description: 'Become a samurai warrior in this epic action game.',
	},
	{
		id: 40,
		title: 'Borderlands 3',
		image: 'https://example.com/borderlands-3.jpg',
		description: 'Loot and shoot your way through the galaxy.',
	},
	{
		id: 41,
		title: 'Star Wars: Squadrons',
		image: 'https://example.com/star-wars-squadrons.jpg',
		description: 'Dogfight in space battles with iconic Star Wars ships.',
	},
]
